server:
  port: 8082
spring:
  profiles:
    active: default
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver
jwt:
  secret: mySecretSignature
  expiration: 900000
  header: X-Auth-Token